export const GET_BOOK_CATEGORIES = "GET_BOOK_CATEGORIES";
export const GET_BOOK_LIST_FOR_GIVEN_CATEGORIES = "GET_BOOK_LIST_FOR_GIVEN_CATEGORIES";

export const GET_BOOK_LIST_FOR_CHILD_BOOKS = "GET_BOOK_LIST_FOR_CHILD_BOOKS";
export const GET_BOOK_LIST_FOR_CLASSIC_BOOKS = "GET_BOOK_LIST_FOR_CLASSIC_BOOKS";
export const GET_BOOK_LIST_FOR_PERSONAL_BOOKS = "GET_BOOK_LIST_FOR_PERSONAL_BOOKS";

export const GET_BOOK_LIST_FOR_MANGA_BOOKS = "GET_BOOK_LIST_FOR_MANGA_BOOKS";
export const GET_BOOK_LIST_FOR_NOVEL_BOOKS = "GET_BOOK_LIST_FOR_NOVEL_BOOKS";
export const GET_BOOK_LIST_FOR_HISTORY_BOOKS = "GET_BOOK_LIST_FOR_HISTORY_BOOKS";

export const SEARCH_BOOK = "SEARCH_BOOK";