export const GET_BOOK_CATEGORIES = "GET_BOOK_CATEGORIES";
export const GET_BOOK_LIST_FOR_GIVEN_CATEGORIES = "GET_BOOK_LIST_FOR_GIVEN_CATEGORIES";

export const GET_BOOK_LIST_FOR_CHILD_BOOKS = "GET_BOOK_LIST_FOR_CHILD_BOOKS";
export const GET_BOOK_LIST_FOR_CLASSIC_BOOKS = "GET_BOOK_LIST_FOR_CLASSIC_BOOKS";